#index:
#    path: /
#    controller: App\Controller\DefaultController::index
homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: index.html.twig

# admin_article_index:
#   path: /admin/article/
#   controller: App\Controller\Admin\ArticleController::index

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"